steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vibes1-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vibes1-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud compute ssh dreamcall-vm \
          --zone=asia-south1-c \
          --command="docker pull gcr.io/$PROJECT_ID/vibes1-app &&
                     docker stop vibes1-container || true &&
                     docker rm vibes1-container || true &&
                     docker run -d --name vibes1-container -p 80:5000 gcr.io/$PROJECT_ID/vibes1-app"

images:
  - 'gcr.io/$PROJECT_ID/vibes1-app'

options:
  logging: CLOUD_LOGGING_ONLY
