steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dreamcall-app', '.']

  # Step 2: Push Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dreamcall-app']

  # Step 3: SSH into VM and run the container
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - dreamcall-vm
      - --zone=asia-south1-c
      - --command
      - |
        "docker pull gcr.io/$PROJECT_ID/dreamcall-app &&
         docker stop dreamcall-container || true &&
         docker rm dreamcall-container || true &&
         docker run -d --name dreamcall-container -p 80:5000 gcr.io/$PROJECT_ID/dreamcall-app"

images:
  - 'gcr.io/$PROJECT_ID/dreamcall-app'

options:
  logging: CLOUD_LOGGING_ONLY
