steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dreamcall-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dreamcall-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'compute', 'instances', 'update-container', 'dreamcall-app',
      '--container-image', 'gcr.io/$PROJECT_ID/dreamcall-app',
      '--zone', 'asia-south1-c'
    ]

images:
  - 'gcr.io/$PROJECT_ID/dreamcall-app'

options:
  logging: CLOUD_LOGGING_ONLY  # ✅ This fixes the build.service_account/logs_bucket error
