name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]  # Or change to your working branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 🔐 Decode GCP credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 -d > ${{ github.workspace }}/gcp-key.json

      - name: 🔑 Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ github.workspace }}/gcp-key.json'

      - name: 🔧 Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: 📦 Configure Docker
        run: |
          gcloud auth configure-docker

      - name: 🐳 Build & Push Docker image
        env:
          PROJECT_ID: commanding-fact-424707-e8
          REGION: us-central1
          SERVICE_NAME: dreamcall-app
        run: |
          IMAGE=gcr.io/$PROJECT_ID/$SERVICE_NAME
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: 🚀 Deploy to Cloud Run
        env:
          PROJECT_ID: commanding-fact-424707-e8
          REGION: us-central1
          SERVICE_NAME: dreamcall-app
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated
